# -*- coding: utf-8 -*-
"""Problem_Two.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ac0S8USh135yWKMY0yhjgnbQKLtTDrOY
"""

# Commented out IPython magic to ensure Python compatibility.
# import any libraries we might need (just listed a few common ones)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame 

# I have little to no experience with what this question is asking so I will carry out my answer under the assumption that question 2 is asking me to simply just prepare a csv file to be used for data exploration.
# Note the values used to answer this question are completely ambiguous and could be changed depending on the tasks requirments due to the vague nature of this question all parameters place holders.

#if needed set some max sizes
pd.set_option('max_columns', 300)
pd.set_option('max_colwidth', 3000)

# render our figure in the notebook to make data easier to read
# %matplotlib inline
plt.rcParams['figure.figsize'] = (12,8)

# Some data cleaning clean out any potential parsing errors and drop cols that have a ton of missing data
data_2017  = pd.read_csv('2017.csv',skiprows=0, low_memory=False)
half = len(data_2017) / 2
data_2017 = data_2017 .dropna(thresh=half,axis=1) # Drop any column with more than 50% missing values

#check to see if data was correctly loaded now we can see the frist 20 index values of data/text
data_2017.head(20)

#number of entries and data rows in our given set
data_2017.shape

#place data in dictionary if needed
dic_2017 = pd.read_csv('2017.csv')
print(dic_2017.shape[0])
print(dic_2017.columns.tolist())
#print current data head
dic_2017.head()

#Rename data rows if needed
Rename = dic_2017.rename(columns={'n/a': 'n/a', 'n/a': 'n/a'})
Rename.head()

#this is totally optional 
data_2017_dtypes = pd.DataFrame(data_2017.dtypes,columns=['dtypes'])
data_2017_dtypes = data_2017_dtypes.reset_index()
data_2017_dtypes['NAME'] = data_2017_dtypes['index']
data_2017_dtypes = data_2017_dtypes[['NAME','dtypes']]
#reposition some of the data and view the index you would like to see
data_2017_dtypes['first value'] = data_2017.loc[2].values
preview = data_2017_dtypes.merge(dic_2017, on='NAME',how='right')
preview.head()